default:
  image: ubuntu:20.04


  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.8 python3-pip
    - apt -y upgrade
    - pip3 install -r requirements.txt


migrations:
  stage: build
  script:

    
django-tests:
  stage: test
  script:
    - # python3 Zoomit-Scraper/script.py

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
